extends SceneTree

func _initialize() -> void:
	var entrance_script = load("res://scripts/world/mobile_entrance.gd")
	assert(entrance_script != null, "mobile entrance renderer exists")
	var root_node := Node3D.new()
	root.add_child(root_node)
	entrance_script.add_to(root_node, Vector3.RIGHT)
	var arch := root_node.get_node_or_null("MobileEntrance/EntranceArch") as MeshInstance3D
	assert(arch != null, "Entrance must have a volumetric masonry arch, not a sprite")
	assert(arch.mesh.resource_path == "res://assets/mobile/entrance-rock-v1.res", "Entrance uses the approved Meshy geometry")
	assert(arch.get_aabb().size.z >= 0.4, "Arch has real tunnel depth")
	assert(root_node.find_children("*", "Sprite3D", true, false).is_empty(), "No baked torch or frontal arch image remains")
	var entrance := root_node.get_node("MobileEntrance")
	assert(entrance.get_node_or_null("WallJoins") != null, "Entrance has masonry wall connectors")
	assert(entrance.get_node("WallJoins").get_child_count() == 2)
	assert(entrance.get_node("Torches").get_child_count() == 2, "Entrance uses two separate wall torch models")
	assert(entrance.get_node_or_null("Steps") == null, "Meshy steps are not covered by duplicate procedural stairs")
	assert(arch.get_aabb().position.y >= -0.001, "Entrance is grounded")
	assert(arch.get_aabb().size.x <= 1.65, "Rock shoulders stay within the entrance surround")
	assert(entrance.find_children("*", "OmniLight3D", true, false).is_empty(), "Entrance reuses budgeted world illumination")
	var other := Node3D.new()
	root.add_child(other)
	entrance_script.add_to(other, Vector3.FORWARD)
	assert(other.get_node("MobileEntrance/EntranceArch").mesh == arch.mesh, "Arch geometry is cached across rebuilds")
	other.free()
	root_node.free()
	print("OK: mobile wall-backed entrance renderer")
	quit()
